// myfile/vue/vue-end/src/scripts/components/counter.vue
<template>
    <div>
        <h2>===============counter </h2>
        <mt-button type="primary" @click="countadd">count++</mt-button>
        <mt-button type="primary" @click="countdesc">count--</mt-button>
        <mt-button type="primary" @click="increment">increment</mt-button>  
        <mt-button type="primary" @click="add">add</mt-button>
        <mt-button type="primary" @click="desc">decrement</mt-button>
        <mt-button type="primary" @click="countadd1">countadd1 100</mt-button>
        <mt-button type="primary" @click="countadd(1000)">countadd</mt-button>
        <mt-button type="primary" @click="changeCity('深圳')">修改你喜欢城市</mt-button>
        <mt-button type="primary" @click="changeMsg({msg:'1803 daydayup'})">修改msg </mt-button>
        <mt-button type="primary" @click="changeUsername({username:'zuzouozmumu'})">修改username </mt-button>
        <mt-button type="primary" @click="changeData({url:'/getdata/123',id:1803})">获取异步数据 data </mt-button>

    </div>
</template>

<script>
import bus from './bus'
import store from "../vuex/store";
import {mapActions} from "vuex";

export default {
    data(){
        return {

        }
    },
    methods:{
        countadd:function(){
            bus.$emit("count-add",10);
        },
        countdesc(){
            bus.$emit("count-desc",100);
        },
        increment2(){
            store.dispatch("increment");  // dispatch action
            // this.$store.dispatch("increment")
        },
        desc(){
            this.$store.dispatch("decrement")
        },
        countadd1(){
            store.dispatch("countadd",100);
        },
        change(e){
            console.log(e.target.value);
        },
        ...mapActions({
            add:"increment",

        }),
        ...mapActions([
            'increment',
            'countadd',  // this.store.dispatch('increment')
            'changeCity',  // store.dispatch("changeCity",'深圳')
            'changeMsg',
            "changeUsername",
            "changeData"
        ])
    }
}
</script>

// myfile/react/react2/src/scripts/redux1/views/counter.js


import React, {Component} from "react"
import store from "../store";

import {Button} from "antd-mobile"
import { changeCity, changeMsg ,ChangeMsgByInp} from "../actions";
export class Counter extends Component{

    componentWillMount(){
        console.log(store);
    }

    change=()=>{
        var value = this.refs.one.value;
        store.dispatch(ChangeMsgByInp(value));
    }

    render(){
        console.log(this.props);
        const {value,count,number,increment,decrement,city,msg } = this.props;
        return (
            <div>
                <h2>redux-demo ---计数器 </h2>
                <h2>count=={value.count}==={count}   </h2>
                <h2>你喜欢的城市   {city}  </h2>
                <p><Button inline size="small" type="primary" >倒计时 {number} 秒</Button></p>
                <p>
                    <Button onClick={()=>store.dispatch( {type:"ADD",payload:100} ) } inline size="small" type="primary"> count ADD </Button>
                    <Button onClick={increment}   inline size="small" type="primary"> increment </Button>
                    <Button onClick={()=>{decrement(20)}}   inline size="small" type="primary"> decrement 20 </Button>
                    <Button onClick={()=>{store.dispatch(changeCity("活泼深圳"))} }   inline size="small" type="primary"> change city 活泼深圳 </Button>
                </p>
                <h1>msg=={msg}</h1>
                <p> 
                    <Button onClick={()=>{store.dispatch(changeMsg("1803 2周 全部就业"))}}   inline size="small" type="primary"> change msg </Button>
                    <input type="text" ref="one" onChange={this.change} />
                </p>
            </div>
        )
    }
}
