// vuex/src/scripts/components/head.vue
<template>
    <mt-header style="background: red" :title="title">
        <mt-button icon="back" slot="left" @click="goback" v-if="show" >返回</mt-button>
        <mt-button icon="more" slot="right" v-if="show" ></mt-button>
    </mt-header>
</template>
<script>
import router from "../router";
export default {
    props:["title","show"],
    methods:{
        goback(){
            console.log(this.$router);
            // this.$router.go(-1);
            router.go(-1);
        }
    }
}
</script>
<style lang="scss">
    // mt-header{background: red}
</style>

// myfile/react/react3/src/scripts/components/head/index.js


import React,{Component} from "react";
import "./index.scss";

import {NavBar,Icon} from "antd-mobile"

export class Head extends Component{

    goback=()=>{
        const {history} = this.props;
        console.log(this.props);
        history.goBack();
    }

    render(){
        const {show,title} = this.props;
        return (
            <NavBar
                mode="dark"
                icon={show?<Icon type="left" />:""}
                leftContent={show?"返回":""}
                onLeftClick={show?this.goback:console.log()}
                rightContent={show?[ <Icon key="1" type="ellipsis" />]:""}
            >{title}</NavBar>
        )
    }
}
