// myfile/react/react1/src/scripts/containers/guide/index.js


import React,{Component} from "react";
import "./index.scss";

import ReactSwipe from "../../components/react-swipe"

export class Guide extends Component{

    state = {
        imgs:[
            require("../../../assets/images/slide1.png"),
            require("../../../assets/images/slide2.png"),
            require("../../../assets/images/slide3.png"),
            require("../../../assets/images/slide4.png"),
        ]
    }

    componentWillMount(){
        const {history} = this.props;
        if(localStorage.visitcount){
            localStorage.visitcount++;
            history.push("/app/")
        }else{
            localStorage.visitcount = 1;
        }
    }

    gotoApp = (index) =>{
        const {history} = this.props;
        if(index==this.state.imgs.length-1){
            history.push("/app/")
        }
    }

    render(){
        const images = this.state.imgs.map((img,index)=>{
            return (<img  onClick={()=>this.gotoApp(index)}  style={{width:"100%",height:"100%"}} src={img} key={index} alt=""/>)
        })
        return (
            <ReactSwipe id="banner" swiperOptions={{resistanceRatio:0,loop:false,autoPlay:1200,speed:1200}}>
                {/* <p>item01</p>
                <p>item02</p>
                <p>item03</p> */}
                {images}
            </ReactSwipe>
        )
    }
}

// myfile/vue/vuex1/src/scripts/views/guide.vue
<template>
    <div class="section">
        <!-- vue-awesome-swiper -->
        <swiper :options="swiperOptions">
            <swiper-slide v-for="(img,index) in imgs " :key="index">
                <img :src="img" alt="" class="img" @click="gotoApp(index)">
            </swiper-slide>
        </swiper>
    </div>
</template>

<script>
import p1 from "../../assets/images/slide1.jpg";
import p2 from "../../assets/images/slide2.jpg";
import p3 from "../../assets/images/slide3.jpg";
import p4 from "../../assets/images/slide4.jpg";

export default {
    data(){
        return {
             imgs:[p1,p2,p3,p4]  ,
             swiperOptions:{
                 loop:false,
                 autoplay:false,
                 speed:2200
             } 
        }
    },
    mounted(){
        if(localStorage.visitCount){
            localStorage.visitCount++;
            // 第二次访问就直接进入主页
            this.$router.push({name:"home"})
        }else{
            // first 1 
            localStorage.visitCount = 1;
        }
    },  
    methods:{
        gotoApp(index){
            if(index==this.imgs.length-1){
                this.$router.push({name:'home'});
            }
        }
    }
}
</script>

<style lang="css" scoped >
    .swiper-container ,.img{
        width:100%;
        height:100%;
    }
</style>
